### ISSUE TITLE
some minor issues with 3.3.0

### ISSUE THREAD

**Issue by ootada** [tim-we/tabs-aside#74] opened 2020-03-03 23:17 UTC
1. window titles seem to be not being set on Firefox restart

2. with "Do not set aside pinned tabs" **unchecked** (I want to save my pinned tabs) and a window containing "about:" (or similar tabs that can't be set aside):
- clicking "tabs aside" / "save tabs as session" reopens all 'saveable' tabs (including pinned) in a new window which is registered as a session window (and closed afterwards for "tabs aside")
- !! **pinned tabs are left unclosed** in the old window along with unsaveable tabs, which gives 2 windows with same pinned tabs when "save tabs as session" as a result (**should be fixed**)
- with windows of some 100+ tabs all of this commotion with new window popping, tabs moving, some not, some in 2 places feels somewhat confusing (and might be an area for improvement), but seems not to lose any tabs in the end (which is a basic expectation :)

3. I would suggest changing the option "Do not set aside pinned tabs" to "Set aside pinned tabs" as negative options are somewhat confusing in general.

thank you.

**Comment by tim-we** [comment] 2020-03-06 21:09
I found the cause of this and I am working on a fix. I will release a patched version on AMO as soon as possible.

**Comment by tim-we** [comment] 2020-03-07 02:15
The fixed version 3.3.1 is now live on AMO. Thanks for submitting this bug! I think changing "Do not set aside pinned tabs" to "Set aside pinned tabs" is a good idea so I will keep this issue open until that is done.

**Comment by ootada** [comment] 2020-04-10 13:18
(1) is still an issue with v3.3.3, window title prefix is lost on firefox restart

**Comment by tim-we** [comment] 2020-04-13 15:57
Oh I forgot about that one, sorry. I think this is a bug with Firefox, since the window title is a property of a window and Firefox does not restore that part. Perhaps we should open an issue on bugzilla...
However even if they accept that as a bug it would take ages for the fix to be shipped so I will fix it.
Probably in the next couple days...

**Comment by tim-we** [comment] 2020-04-16 22:57
As of version 3.3.4 the title prefix should be restored. The new version is available.

**Comment by tim-we** [comment] 2020-04-22 22:05
> I would suggest changing the option "Do not set aside pinned tabs" to "Set aside pinned tabs" as negative options are somewhat confusing in general.

Done! Will be part of the next release.

**Closed by tim-we** 2020-04-22 22:05 UTC
Labels: enhancement
