### ISSUE TITLE
"New session title template" not working

### ISSUE THREAD

**Issue by egabrum** [tim-we/tabs-aside#92] opened 2020-07-30 17:03 UTC
I'm trying the new "New session title template" feature, with and without variables, but all my session end up being named "session"

Firefox 79.0
Tabs Aside 3.4.0

**Comment by tim-we** [comment] 2020-07-30 18:00
Hmm I cannot reproduce that, seems to be working as expected for me (and also for a friend with a different setup). However I am still using FF 78, I will try 79 later.
What is the template you are using?
Also just to be clear, this should only have an effect on new sessions, created after updating the title template.

**Comment by egabrum** [comment] 2020-07-31 09:26
Interesting. I just cannot get it to work.
I have tried templates with variables (Session $d.$M. - $Hh) and without (test). The sessions are created always with the same name (session).

**Comment by tim-we** [comment] 2020-07-31 09:54
Can you try to restart the addon (disable & re-enable) or even restart Firefox?
How do you have Tabs Aside configured? (I just tested it with active sessions disabled and enabled, both work for me)

**Comment by egabrum** [comment] 2020-07-31 10:14
OK, I see now. I don't use the drop-down menu from the icon in the Extension bar. I find there are not enough options and, for the one the are there, it's not too clear for me what they do from just the title ("Tabs aside", "Save tabs as session"). I'd prefer: 
"Set all tabs aside in new session > (new session/existing sessions)", 
"Save all tabs in new session > (new session/existing sessions)", 
"Set selected tabs aside in... > (new session/existing sessions)",  
"Save selected in... > (new session/existing sessions)"

...but this is a different issue.

The problem here is that I use a different path:
Select 1 or more tabs > Right click > Tabs Aside! > [...] > create new session.

Following this path, the title is always 'session'

**Comment by tim-we** [comment] 2020-07-31 19:17
Thanks for submitting this bug. I just committed a fix. The fix will be included in the next update.

**Comment by tim-we** [comment] 2020-08-03 21:38
The update (3.5.0) is now live.

**Closed by tim-we** 2020-08-03 21:38 UTC
Labels: bug, implemented
