### ISSUE TITLE
Every site showing up as bookmarked

### ISSUE THREAD

**Issue by CorePoint** [tim-we/tabs-aside#81] opened 2020-06-04 18:47 UTC
Every site I go to is showing up as bookmarked to the folder "New Session" since some time.
I'm pretty sure that's not how it was before. Seems to be like this since 3.4.

Also thank you for providing us with this piece of software. :)

**Comment by tim-we** [comment] 2020-06-04 19:37
This is expected behavior if your current window is an active session. Active sessions track changes in their window and update the bookmarks accordingly. If you don't want that you can open the sidebar (`Alt+Q`), find the active session (seems to be called New Session, which is the default) and click the three dots next to "Set aside" and click remove. After the confirmation it will ask you if you want to keep the tabs open, the bookmarks will be deleted.
You can also disable active sessions in the options, however this will not affect currently active sessions.

In case you were aware of this and this is an actual issue I need some more details as for me it's all working as it should. You could perhaps try to turn Tabs Aside off and on again by disabling and re-enabling it. Hope this helps :)

**Comment by CorePoint** [comment] 2020-06-04 19:44
Hey, thanks for the quick answer and sorry for the false bug report!
Can i ask you when this functionality was added, or if it was there from the beginning?
Can't find anything about it in the changelogs. Just wondering why I am just seeing this now.

**Comment by tim-we** [comment] 2020-06-04 20:00
No problem, I know not all the functionality is clearly communicated - that is another issue.
Active sessions have been introduced in Tabs Aside 2.0 which was released in April 2018 ;)

**Closed** 2020-06-04 20:04 UTC

**Comment by CorePoint** [comment] 2020-06-04 20:23
Wow since 2018, that makes it so more weirder. Just to clarify, is the bookmark symbol (star) in the adress bar also filled out blue for every site you visit when active session are activated?
Because I'm like 99% sure that this is a new thing for me, maybe there is something on Mozillas side that changed.

**Comment by tim-we** [comment] 2020-06-04 20:30
Well Tabs Aside stores sessions as bookmark folder containing bookmarks for every tab. The bookmark star indicates that there exists a bookmark for that page somewhere, including the Tabs Aside folders. If a window is an active session it will create a new bookmark for every new tab you open and update the bookmark accordingly every time you navigate thus always showing the bookmark star in blue. I chose bookmarks for storage as that keeps the user in full control of the data and also synchronizes across devices.

**Comment by CorePoint** [comment] 2020-06-04 20:37
Alright that's exactly what I thought and also the reason why I'm so weirded out by just seeing this behavior now. I thought maybe the UI woudn't reflect it because it happens automatically or something, that's why I asked.

When I think about it I have a vague recollection of the Setup assistant asking be to setup the Add-on again recently, I probably just blitzed through that and that's why I had the option enabled since then.

Thank you for your elaborate answers by the way!
