### ISSUE TITLE
[Bug] Tabs You've Set Aside Sidebar slow to load in Firefox 89

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#114] opened 2021-06-01 14:21 UTC
The Firefox 89 Photon Design refresh was released today.

Tabs-aside actually works better because the interface does not hang up anymore.

The only thing is that the Sidebar takes much longer to load (I have to wait a few minutes for the folders to show.

Otherwise, the addon is working perfectly and better than ever.

**Comment by tim-we** [comment] 2021-06-01 15:02
Thanks for letting me know, I will kook into it when I get the new version.

**Comment by tim-we** [comment] 2021-06-03 22:55
I cannot reproduce this behavior, the sidebar loads basically instantaneous for me. How many sessions do you have?

**Comment by sahil48** [comment] 2021-06-04 12:49
Turns out there are a lot of sessions. I have one saved every other day, and return back to them randomly so about 1 or 2 years worth of sessions. That's probably what's bogging it down, and I can move older bookmarks out into another folder.

**Comment by tim-we** [comment] 2021-06-05 11:26
That sounds like a lot of sessions. Tabs Aside is not really optimized for this, not sure if it should. But regardless I don't think this has anything to do with Firefox 89 vs previous versions so I am closing this issue.

**Closed by tim-we** 2021-06-05 11:26 UTC
